import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,existsSync,readFileSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {ObservationStore} from '../src/store.ts';
import {capture,NOW} from './helpers.ts';
function setup(fn){const dir=mkdtempSync(join(tmpdir(),'pi-archive-'));const store=new ObservationStore(join(dir,'source.sqlite'));try{fn(store,dir);}finally{store.close();rmSync(dir,{recursive:true,force:true});}}
function resign(a){const {sha256,...body}=a;return {...body,sha256:createHash('sha256').update(JSON.stringify(body)).digest('hex')};}
function restore(file,db){return spawnSync(process.execPath,['src/cli.ts','restore','--file',file,'--db',db],{encoding:'utf8'});}
test('backup round trip preserves evidence corrections targets and timestamps',()=>setup((s,dir)=>{s.ingest(capture(),NOW);s.decide('fixture-001','uncertain','RECHECK_REQUIRED');const t=s.saveTarget({url:'https://amazon.com/dp/EXAMPLE',label:'Display',targetMinor:80000});s.archiveTarget(t.id,true);const data=s.exportArchive();const file=join(dir,'export.json');writeFileSync(file,JSON.stringify(data));const dest=join(dir,'restored.sqlite');const r=restore(file,dest);assert.equal(r.status,0,r.stderr);const other=new ObservationStore(dest);try{assert.deepEqual(other.inspect('fixture-001'),s.inspect('fixture-001'));assert.deepEqual(other.targets({includeArchived:true}),s.targets({includeArchived:true}));assert.equal(other.summary({includeSynthetic:true}).uncertain,1);}finally{other.close();}}));
test('backup checksum detects corruption and failed restore leaves no destination',()=>setup((s,dir)=>{s.ingest(capture(),NOW);const a=s.exportArchive();a.observations[0].capture.candidates[0].price='1.00';const file=join(dir,'bad.json'),dest=join(dir,'new.sqlite');writeFileSync(file,JSON.stringify(a));const r=restore(file,dest);assert.equal(r.status,1);assert.match(r.stderr,/ARCHIVE_CHECKSUM_MISMATCH/);assert.equal(existsSync(dest),false);}));
test('restore refuses existing destination without modifying its bytes',()=>setup((s,dir)=>{const file=join(dir,'empty.json');writeFileSync(file,JSON.stringify(s.exportArchive()));const dest=join(dir,'existing.sqlite');writeFileSync(dest,'keep this');assert.equal(restore(file,dest).status,1);assert.equal(readFileSync(dest,'utf8'),'keep this');}));
test('resigned archive cannot promote originally uncertain capture',()=>setup((s,dir)=>{const c=capture();c.candidates.pop();s.ingest(c,NOW);const a=s.exportArchive();a.observations[0].decisions.push({status:'accepted',reason:'RECHECK_CONFIRMED',decidedAt:'2026-10-01T12:00:00.000Z'});const file=join(dir,'forged.json'),dest=join(dir,'new.sqlite');writeFileSync(file,JSON.stringify(resign(a)));const r=restore(file,dest);assert.equal(r.status,1);assert.match(r.stderr,/ORIGINAL_NOT_ACCEPTED/);assert.equal(existsSync(dest),false);}));
test('resigned archive with an invalid event timestamp is rejected',()=>setup((s,dir)=>{s.ingest(capture(),NOW);const a=s.exportArchive();a.observations[0].decisions.push({status:'rejected',reason:'RECHECK_REQUIRED',decidedAt:'2020-02-31T00:00:00.000Z'});const file=join(dir,'old.json'),dest=join(dir,'new.sqlite');writeFileSync(file,JSON.stringify(resign(a)));assert.equal(restore(file,dest).status,1);assert.equal(existsSync(dest),false);}));
test('CLI backup refuses overwriting existing files and writes a recoverable archive',()=>setup((s,dir)=>{s.ingest(capture(),NOW);const file=join(dir,'backup.json');const args=['src/cli.ts','backup','--file',file,'--db',join(dir,'source.sqlite')];const first=spawnSync(process.execPath,args,{encoding:'utf8'});assert.equal(first.status,0,first.stderr);assert.equal(JSON.parse(readFileSync(file,'utf8')).observations.length,1);const bytes=readFileSync(file);assert.equal(spawnSync(process.execPath,args,{encoding:'utf8'}).status,1);assert.deepEqual(readFileSync(file),bytes);}));
test('restore refuses destination sidecars and leaves unrelated files intact',()=>setup((s,dir)=>{const file=join(dir,'export.json'),dest=join(dir,'new.sqlite');writeFileSync(file,JSON.stringify(s.exportArchive()));writeFileSync(dest+'-wal','keep this sidecar');const r=restore(file,dest);assert.equal(r.status,1);assert.equal(existsSync(dest),false);assert.equal(readFileSync(dest+'-wal','utf8'),'keep this sidecar');}));
test('explicit replay clock is preserved independently of backup wall time',()=>setup((s,dir)=>{const later='2030-01-01T00:00:00.000Z';s.ingest(capture({observedAt:later}),later);s.decide('fixture-001','uncertain','RECHECK_REQUIRED');const file=join(dir,'replay.json'),dest=join(dir,'new.sqlite');writeFileSync(file,JSON.stringify(s.exportArchive()));const r=restore(file,dest);assert.equal(r.status,0,r.stderr);const other=new ObservationStore(dest);try{assert.equal(other.inspect('fixture-001').currentStatus,'uncertain');assert.equal(other.inspect('fixture-001').decisions[0].decidedAt,later);}finally{other.close();}}));
test('legacy Unicode capture URLs remain recoverable and queryable',()=>setup((s,dir)=>{s.ingest(capture({url:'https://amazon.com/'+'品'.repeat(1500)}),NOW);const file=join(dir,'legacy.json'),dest=join(dir,'new.sqlite');writeFileSync(file,JSON.stringify(s.exportArchive()));const r=restore(file,dest);assert.equal(r.status,0,r.stderr);const other=new ObservationStore(dest);try{const h=other.offerHistory({includeSynthetic:true});assert.ok(h.items[0].offerKey.length>8192);assert.equal(other.series(h.items[0].offerKey,{includeSynthetic:true}).items.length,1);assert.equal(other.offerHistory({includeSynthetic:true,after:h.items[0].offerKey}).items.length,0);}finally{other.close();}}));
