import {test} from 'node:test';
import assert from 'node:assert/strict';
import {parseMoney, canonicalUrl, validGtin} from '../src/validation.ts';
import {matchIdentity} from '../src/identity.ts';
import {evaluate} from '../src/engine.ts';
import {capture, NOW, product} from './helpers.ts';

for (const [value,expected] of [['899.99',89999],['1,099.00',109900],[19.5,1950],['0.01',1]]) test(`money ${value}`,()=>assert.equal(parseMoney(value),expected));
for (const value of ['99/mo','1e3','-1','0','1.001','1,00.00','1 000','100-200','',NaN,Infinity,null,{},'900719925474099.99']) test(`reject money ${String(value)}`,()=>assert.throws(()=>parseMoney(value)));
test('canonical URL',()=>assert.equal(canonicalUrl('https://www.amazon.com/dp/EXAMPLE/'),'https://amazon.com/dp/EXAMPLE'));
for (const url of ['http://amazon.com/x','https://amazon.com.evil.test/x','https://localhost/x','https://127.0.0.1/x','https://user:pass@amazon.com/x','https://amazon.com:444/x','https://amazon.com/x?token=secret','https://amazon.com/x#secret','https://amazon.com/%2fadmin','https://amazon.com./x']) test(`reject URL ${url}`,()=>assert.throws(()=>canonicalUrl(url)));
test('GTIN checksum',()=>{assert.equal(validGtin('4006381333931'),true);assert.equal(validGtin('4006381333932'),false);assert.equal(validGtin('0000000000000'),false);});
test('exact identity',()=>assert.equal(matchIdentity(product,{...product}).match,true));
for (const patch of [{variant:'white-single'},{gtin:'012345678905'},{mpn:'EX-28'},{model:'DISPLAY-28'},{brand:'Another'}]) test(`identity conflict ${JSON.stringify(patch)}`,()=>assert.equal(matchIdentity(product,{...product,...patch}).match,false));
test('MPN fallback requires variant',()=>{assert.equal(matchIdentity({...product,gtin:null},{...product,gtin:null}).match,true);assert.equal(matchIdentity({...product,variant:null},{...product,variant:null}).match,false);});
test('two scoped channels accept',()=>{const r=evaluate(capture(),NOW);assert.equal(r.status,'accepted');assert.equal(r.offer?.priceMinor,89999);assert.equal(r.offer?.shippingMinor,null);});
test('same underlying origin does not count twice',()=>{const c=capture(); c.candidates[1]={...c.candidates[0]};assert.equal(evaluate(c,NOW).status,'uncertain');});
test('conflicting price quarantines',()=>{const c=capture();c.candidates[1].price='799.99';const r=evaluate(c,NOW);assert.equal(r.status,'uncertain');assert.ok(r.reasons.includes('PRICE_CONFLICT'));});
test('reference and financing never enter current price',()=>{const c=capture();c.candidates.push({...c.candidates[0],role:'reference',price:'1099.99'},{...c.candidates[0],role:'financing',price:'74.99'});assert.equal(evaluate(c,NOW).offer?.priceMinor,89999);});
for (const field of ['seller','condition','availability','currency','eligibility','fulfillment'] as const) test(`unknown ${field} quarantines`,()=>{const c=capture();for(const a of c.candidates) a[field]=null;assert.equal(evaluate(c,NOW).status,'uncertain');});
test('unknown role cannot be hidden',()=>{const c=capture();c.candidates.push({...c.candidates[0],role:'unknown'});assert.equal(evaluate(c,NOW).status,'uncertain');});
test('conditional offer quarantines',()=>{const c=capture();for(const a of c.candidates)a.eligibility='membership';assert.equal(evaluate(c,NOW).status,'uncertain');});
test('other seller cannot corroborate',()=>{const c=capture();c.candidates[1].seller='Other Retail';assert.equal(evaluate(c,NOW).status,'uncertain');});
test('incorrect selected product cannot pass',()=>{const c=capture();c.context.product={...product,model:'DISPLAY-28'};assert.equal(evaluate(c,NOW).status,'uncertain');});
test('stale capture rejected',()=>assert.equal(evaluate(capture({observedAt:'2026-01-01T12:00:00.000Z'}),NOW).status,'rejected'));
test('future source time rejected',()=>assert.equal(evaluate(capture({sourceObservedAt:'2026-01-16T12:00:00.000Z'}),NOW).status,'rejected'));
test('stale upstream time rejected',()=>assert.equal(evaluate(capture({sourceObservedAt:'2026-01-10T12:00:00.000Z'}),NOW).status,'rejected'));
test('malformed timestamps rejected',()=>assert.equal(evaluate(capture({observedAt:'yesterday'}),NOW).status,'rejected'));
test('bad input rejected without throwing',()=>{for(const input of [null,{},[],{...capture(),candidates:'oops'},{...capture(),decision:'accepted'}]) assert.equal(evaluate(input,NOW).status,'rejected');});
test('provenance mismatch rejected',()=>assert.equal(evaluate(capture({synthetic:false}),NOW).status,'rejected'));
test('too many candidates rejected',()=>{const c=capture();c.candidates=Array(101).fill(c.candidates[0]);assert.equal(evaluate(c,NOW).status,'rejected');});
test('parser issues quarantine even agreeing candidates',()=>assert.equal(evaluate(capture({issues:['MALFORMED_JSONLD']}),NOW).status,'uncertain'));
test('out of stock accepted as non-purchasable evidence',()=>{const c=capture();for(const a of c.candidates)a.availability='out-of-stock';assert.equal(evaluate(c,NOW).offer?.purchasable,false);});
for(const [field,value] of [['gtin','012345678905'],['mpn','EX-28'],['model','DISPLAY-28']]) test(`cross-evidence ${field} conflict with incomplete context`,()=>{
  const c=capture();c.context.product={...product,[field]:null};c.candidates[1].product={...product,[field]:value};
  const r=evaluate(c,NOW);assert.equal(r.status,'uncertain');assert.ok(r.reasons.includes('CANDIDATE_IDENTITY_CONFLICT'));
});
test('array provenance cannot launder a synthetic capture',()=>assert.equal(evaluate(capture({method:['synthetic-fixture'],synthetic:false}),NOW).status,'rejected'));
test('array source cannot impersonate a channel',()=>{const c=capture();const candidates=[{...c.candidates[0],source:['jsonld']},...c.candidates.slice(1)];assert.equal(evaluate({...c,candidates},NOW).status,'rejected');});
