import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {request} from 'node:http';
import {startApp} from '../src/server.ts';
import {capture,NOW} from './helpers.ts';
type App=Awaited<ReturnType<typeof startApp>>;
type Api=(path:string,body?:unknown,headers?:Record<string,string>)=>Promise<Response>;
async function run(fn:(app:App,api:Api)=>Promise<void>){const dir=mkdtempSync(join(tmpdir(),'pi-http-'));const app=await startApp({dbPath:join(dir,'db.sqlite'),port:0});const api:Api=async(path,body,headers={})=>fetch(app.url+path,{method:body===undefined?'GET':'POST',headers:{Authorization:'Bearer '+app.token,...(body===undefined?{}:{'Content-Type':'application/json'}),...headers},body:body===undefined?undefined:JSON.stringify(body)});try{await fn(app,api);}finally{await app.close();rmSync(dir,{recursive:true,force:true});}}
test('local API requires token and refuses cross-origin callers',()=>run(async(app,api)=>{const address=app.server.address();assert.ok(address&&typeof address==='object');assert.equal(address.address,'127.0.0.1');assert.equal((await fetch(app.url+'/api/summary')).status,401);assert.equal((await api('/api/summary',undefined,{Authorization:'Bearer wrong'})).status,401);assert.equal((await api('/api/summary',undefined,{Origin:'https://evil.example'})).status,403);assert.equal((await api('/api/summary',undefined,{'Sec-Fetch-Site':'cross-site'})).status,403);assert.equal((await api('/api/summary',undefined,{Origin:app.url})).status,200);}));
test('local service rejects DNS rebinding host and unexpected method',()=>run(async(app,api)=>{const status=await new Promise((resolve,reject)=>{const req=request(app.url+'/api/summary',{headers:{Host:'evil.example',Authorization:'Bearer '+app.token}},r=>{r.resume();resolve(r.statusCode);});req.on('error',reject);req.end();});assert.equal(status,403);assert.equal((await fetch(app.url+'/api/summary',{method:'DELETE',headers:{Authorization:'Bearer '+app.token}})).status,405);}));
test('HTTP import review targets history and backup use the actual persisted store',()=>run(async(app,api)=>{let r=await api('/api/import',{capture:capture(),at:NOW});assert.equal(r.status,201);assert.equal((await r.json()).evaluation.status,'accepted');let a=await (await api('/api/observations?synthetic=1')).json();assert.equal(a.items[0].id,'fixture-001');assert.equal((await (await api('/api/summary')).json()).total,0);r=await api('/api/decisions',{id:'fixture-001',status:'uncertain',reason:'RECHECK_REQUIRED'});assert.equal((await r.json()).currentStatus,'uncertain');assert.equal((await (await api('/api/history?synthetic=1')).json()).items.length,0);r=await api('/api/targets',{url:'https://amazon.com/dp/EXAMPLE',label:'Display',targetMinor:80000});assert.equal(r.status,201);assert.equal((await (await api('/api/targets')).json()).length,1);const backup=await (await api('/api/backup')).json();assert.equal(backup.observations.length,1);assert.equal(backup.targets.length,1);}));
test('HTTP parser refuses non-JSON oversized malformed and unsupported fields without leaking input',()=>run(async(app,api)=>{assert.equal((await api('/api/import',{}, {'Content-Type':'text/plain'})).status,415);let r=await fetch(app.url+'/api/import',{method:'POST',headers:{Authorization:'Bearer '+app.token,'Content-Type':'application/json'},body:'{"private":"bad'});assert.equal(r.status,400);assert.doesNotMatch(await r.text(),/private/);r=await api('/api/import',{capture:capture(),at:NOW,unexpected:true});assert.equal(r.status,400);r=await api('/api/import',{padding:'x'.repeat(4*1024*1024)});assert.equal(r.status,413);assert.equal((await api('/api/observations?limit=201')).status,400);assert.equal((await api('/api/observations?synthetic=oops')).status,400);}));
test('demo is explicitly synthetic and static assets cannot expose private files or the token',()=>run(async(app,api)=>{let r=await api('/api/demo',{});assert.equal(r.status,201);assert.equal((await (await api('/api/summary')).json()).total,0);assert.ok((await (await api('/api/summary?synthetic=1')).json()).total>0);r=await fetch(app.url+'/');assert.equal(r.status,200);assert.match(r.headers.get('content-security-policy')??'',/default-src 'self'/);const html=await r.text();assert.doesNotMatch(html,new RegExp(app.token));assert.match(html,/Product Intelligence/);for(const path of ['/data/observations.sqlite','/src/store.ts','/.env','/api/unknown'])assert.equal((await api(path)).status,404);}));
test('malformed non-ASCII bearer token is refused as authentication failure',()=>run(async(app,api)=>{const response=await api('/api/summary',undefined,{Authorization:'Bearer '+app.token.slice(0,-1)+'é'});assert.equal(response.status,401);}));
test('long valid offer identities remain inspectable through bounded JSON read requests',()=>run(async(app,api)=>{const c=capture({url:'https://amazon.com/'+'x'.repeat(1500)});const context={...c.context,product:{...c.context.product,brand:'品'.repeat(160),model:'品'.repeat(160),mpn:'品'.repeat(160),variant:'品'.repeat(160)},seller:'品'.repeat(160)};c.context=context;for(const candidate of c.candidates)Object.assign(candidate,context);assert.equal((await api('/api/import',{capture:c,at:NOW})).status,201);let r=await api('/api/history',{includeSynthetic:true,limit:1});assert.equal(r.status,200);const h=await r.json();const key=h.items[0].offerKey;assert.ok(new URLSearchParams({key}).toString().length>8192);r=await api('/api/series',{key,includeSynthetic:true});assert.equal(r.status,200);assert.equal((await r.json()).items[0].id,c.id);r=await api('/api/history',{after:key,includeSynthetic:true});assert.equal(r.status,200);assert.equal((await r.json()).items.length,0);}));
