import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {ObservationStore} from '../src/store.ts';
import {capture,NOW} from './helpers.ts';
function run(fn:(store:ObservationStore,path:string)=>void) {const dir=mkdtempSync(join(tmpdir(),'pi-workspace-'));const path=join(dir,'db.sqlite');const s=new ObservationStore(path);try{fn(s,path);}finally{s.close();rmSync(dir,{recursive:true,force:true});}}
test('workspace summary reflects corrections and excludes synthetic by default',()=>run(s=>{s.ingest(capture(),NOW);assert.deepEqual(s.summary(),{total:0,accepted:0,uncertain:0,rejected:0});assert.equal(s.summary({includeSynthetic:true}).accepted,1);s.decide('fixture-001','uncertain','RECHECK_REQUIRED');assert.equal(s.summary({includeSynthetic:true}).uncertain,1);assert.equal(s.summary({includeSynthetic:true}).accepted,0);}));
test('observation paging has no duplicates when new captures arrive',()=>run(s=>{for(let i=0;i<3;i++)s.ingest(capture({id:'item-'+i}),NOW);const a=s.list({includeSynthetic:true,limit:2});assert.deepEqual(a.items.map(x=>x.id),['item-2','item-1']);s.ingest(capture({id:'new'}),NOW);const b=s.list({includeSynthetic:true,limit:2,after:a.nextCursor});assert.deepEqual(b.items.map(x=>x.id),['item-0']);assert.equal(b.nextCursor,null);}));
test('observation search returns selected product and current review status',()=>run(s=>{s.ingest(capture(),NOW);s.decide('fixture-001','rejected','WRONG_PRODUCT');assert.equal(s.list({includeSynthetic:true,status:'accepted'}).items.length,0);const list=s.list({includeSynthetic:true,status:'rejected',query:'display-27'});assert.equal(list.items[0].status,'rejected');assert.equal(list.items[0].priceMinor,89999);assert.equal(s.list({includeSynthetic:true,query:'%'}).items.length,0);}));
test('workspace rejects invalid limits cursors and filters',()=>run(s=>{for(const options of [{limit:0},{limit:201},{after:'x'},{after:-1},{status:'oops'},{query:'x'.repeat(201)}])assert.throws(()=>s.list(options),/INVALID_/);}));
test('decision pages are bounded and preserve correction order',()=>run(s=>{s.ingest(capture(),NOW);s.decide('fixture-001','uncertain','RECHECK_REQUIRED');s.decide('fixture-001','accepted','RECHECK_CONFIRMED');const first=s.inspect('fixture-001',{limit:2});assert.equal(first.decisions.length,2);assert.equal(first.currentStatus,'accepted');assert.equal(first.decisionCount,3);const second=s.inspect('fixture-001',{after:first.nextCursor,limit:2});assert.equal(second.decisions[0].reason,'RECHECK_CONFIRMED');assert.equal(second.nextCursor,null);}));
test('offer aggregate and series preserve exact context and chronological ties',()=>run(s=>{s.ingest(capture({id:'b'}),NOW);const low=capture({id:'a'});for(const c of low.candidates)c.price='799.00';s.ingest(low,NOW);let h=s.offerHistory({includeSynthetic:true});assert.equal(h.items.length,1);assert.equal(h.items[0].sampleCount,2);assert.equal(h.items[0].lowestObservedMinor,79900);assert.equal(h.items[0].latestObservedMinor,89999);const key=h.items[0].offerKey;const a=s.series(key,{includeSynthetic:true,limit:1});assert.equal(a.items[0].id,'a');assert.equal(s.series(key,{includeSynthetic:true,after:a.nextCursor}).items[0].id,'b');assert.equal(s.series(key).items.length,0);s.decide('b','rejected','WRONG_PRODUCT');assert.equal(s.offerHistory({includeSynthetic:true}).items[0].latestObservedMinor,79900);}));
test('targets normalize URLs and persist threshold and reversible archive',()=>run((s,path)=>{let t=s.saveTarget({url:'https://www.bestbuy.com/site/example/123.p/',label:'Office display',targetMinor:80000});assert.equal(t.url,'https://bestbuy.com/site/example/123.p');const again=s.saveTarget({url:t.url,label:'Display',targetMinor:null});assert.equal(again.id,t.id);assert.equal(s.targets().length,1);s.archiveTarget(t.id,true);assert.equal(s.targets().length,0);s.archiveTarget(t.id,false);const other=new ObservationStore(path);try{assert.equal(other.targets()[0].label,'Display');assert.equal(other.targets()[0].targetMinor,null);}finally{other.close();}}));
test('targets reject invalid URL labels and prices without writes',()=>run(s=>{for(const changes of [{url:'https://localhost/private'},{label:''},{label:'x'.repeat(121)},{targetMinor:-1},{targetMinor:1.5},{targetMinor:Number.MAX_SAFE_INTEGER+1}])assert.throws(()=>s.saveTarget({url:'https://amazon.com/dp/EXAMPLE',label:'Display',targetMinor:100,...changes}));assert.equal(s.targets().length,0);assert.throws(()=>s.archiveTarget('missing',true),/NOT_FOUND/);}));
test('schema-one observations survive the schema-two migration',()=>{const dir=mkdtempSync(join(tmpdir(),'pi-migrate-'));const path=join(dir,'db.sqlite');try{let s=new ObservationStore(path);s.ingest(capture(),NOW);s.close();let db=new DatabaseSync(path);db.exec('DROP TABLE IF EXISTS watch_targets; PRAGMA user_version=1');db.close();s=new ObservationStore(path);try{assert.equal(s.inspect('fixture-001').evaluation.status,'accepted');assert.equal(s.targets().length,0);}finally{s.close();}}finally{rmSync(dir,{recursive:true,force:true});}});
test('targets reject a URL whose canonical encoded form exceeds the supported limit',()=>run(s=>{assert.throws(()=>s.saveTarget({url:'https://amazon.com/'+'品'.repeat(300),label:'Display',targetMinor:null}),/UNSAFE_URL/);assert.equal(s.targets().length,0);}));
