import {requestGate,archiveText} from './requests.js';
import {escapeHTML as e,money,productName,date,badge,ageLabel,targetPrice,priceChart,observationTable} from './view.js';
const detailGate=requestGate(),viewGate=requestGate();
const $=id=>document.getElementById(id),screen=$('screen'),dialog=$('detail');
const names={overview:['Overview','A clear view of the evidence you have collected.'],observations:['Observations','Inspect captures and resolve uncertain evidence.'],history:['Price history','Accepted, in-stock observations grouped by the exact offer.'],targets:['Watch targets','Keep the listings you want to research in one place.'],import:['Import evidence','Bring saved captures into your private workspace.'],backup:['Backup & recovery','Keep a recoverable copy of your evidence and decisions.']};
let token=sessionStorage.getItem('pi-session')??'',route='overview',generation=0,rows=[],next=null,filters={query:'',status:''},activeDetail=null,historyRows=[],seriesRows=[],seriesNext=null;
function consumeSessionLink(){if(location.hash.startsWith('#token=')){token=new URLSearchParams(location.hash.slice(1)).get('token')??'';if(/^[a-f0-9]{64}$/.test(token))sessionStorage.setItem('pi-session',token);else{token='';sessionStorage.removeItem('pi-session');}history.replaceState(null,'',location.pathname+'#overview');}}
consumeSessionLink();
function notice(message,error=false){$('notice').className=message?'notice'+(error?' error':''):'';$('notice').textContent=message;}
async function api(path,data){const requestToken=token;const response=await fetch('/api/'+path,{method:data===undefined?'GET':'POST',headers:{Authorization:'Bearer '+requestToken,...(data===undefined?{}:{'Content-Type':'application/json'})},body:data===undefined?undefined:JSON.stringify(data)});const result=await response.json();if(!response.ok){if(response.status===401&&token===requestToken){sessionStorage.removeItem('pi-session');token='';}throw new Error(result.error??'REQUEST_FAILED');}return result;}
function params(extra={}){const p=new URLSearchParams({synthetic:$('synthetic').checked?'1':'0',...extra});for(const [k,v]of [...p])if(v===''||v==='null'||v==='undefined')p.delete(k);return p.toString();}
const more=()=>next!==null?'<button class="secondary more" data-action="more">Load more</button>':'';
const panel=(title,body)=>`<section class="panel"><h2>${title}</h2>${body}</section>`;
function authScreen(){screen.innerHTML=panel('Open your private session','<p>Start the app with <code>npm start</code>, then open the private link printed in that terminal. The session link changes whenever the app restarts.</p><p>No data is sent to an external service.</p>');}
async function render(reset=true){
 route=location.hash.slice(1)||'overview';if(!Object.hasOwn(names,route))route='overview';const ticket=++generation;
 $('page-title').textContent=names[route][0];$('subtitle').textContent=names[route][1];document.title=names[route][0]+' · Product Intelligence';
 for(const a of document.querySelectorAll('nav a')){if(a.hash==='#'+route)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');}
 if(!token){authScreen();return;}if(reset){rows=[];next=null;}screen.setAttribute('aria-busy','true');if(reset)screen.innerHTML='<p class="loading">Loading your workspace…</p>';
 try{
  let html='';
  if(route==='overview'){
   const [counts,recent,targets]=await Promise.all([api('summary?'+params()),api('observations?'+params({limit:5})),api('targets')]);
   html=`<div class="stats">${[['All observations',counts.total],['Accepted',counts.accepted],['Needs review',counts.uncertain],['Watch targets',targets.length]].map(([label,n])=>`<div class="stat"><span>${label}</span><strong>${n}</strong></div>`).join('')}</div><div class="callout"><p><strong>Your evidence workspace is ready.</strong> Import saved captures to build a trustworthy price history.</p><small>Live collection is not configured. Watch targets do not make network requests.</small></div><section class="panel"><div class="panel-head"><h2>Recent observations</h2><a href="#observations">View all</a></div>${observationTable(recent.items)}</section><div class="columns">${panel('Start with real evidence','<p>Import a normalized JSON capture or saved HTML with its capture metadata. Missing context stays uncertain until new evidence resolves it.</p><a class="button" href="#import">Import evidence</a>')}${panel('Explore with a sample','<p>A labeled synthetic capture demonstrates the review and history workflow.</p><button class="secondary" data-action="demo">Load synthetic sample</button>')}</div>`;
  }else if(route==='observations'){
   const data=await api('observations?'+params({...filters,after:next}));if(ticket!==generation)return;rows.push(...data.items);next=data.nextCursor;
   html=`<form id="search-form" class="toolbar"><label>Product or listing<input name="query" type="search" maxlength="200" value="${e(filters.query)}" placeholder="Search model, brand or URL"></label><label>Review status<select name="status">${[['','All statuses'],['accepted','Accepted'],['uncertain','Uncertain'],['rejected','Rejected']].map(([value,label])=>`<option value="${value}" ${filters.status===value?'selected':''}>${label}</option>`).join('')}</select></label><button>Apply filters</button></form><section class="panel">${observationTable(rows)}${more()}</section>`;
  }else if(route==='history'){
   const data=await api('history',{includeSynthetic:$('synthetic').checked,after:next});if(ticket!==generation)return;rows.push(...data.items);next=data.nextCursor;historyRows=rows;
   html=rows.length?`<p class="muted">Each row is a separate listing, variant, seller, condition and fulfillment context. Select one to inspect its dated observations.</p>${rows.map((r,i)=>`<button class="history-item" data-history="${i}"><span><strong>${e(productName(r.product))}</strong><small>${e(r.seller)} · ${e(r.condition)} · ${e(r.product.variant)} · ${e(r.fulfillment)}</small><small>${e(new URL(r.url).hostname)} · ${r.sampleCount} observations ${r.containsSynthetic?'· Synthetic':''}</small></span><span><small>Latest observed</small><strong>${money(r.latestObservedMinor)}</strong><small>${e(date(r.lastObservedAt))}</small></span><span><small>Lowest observed</small><strong>${money(r.lowestObservedMinor)}</strong></span><span><small>Highest observed</small><strong>${money(r.highestObservedMinor)}</strong></span></button>`).join('')}${more()}`:panel('No accepted price history yet','<p>Accepted, in-stock observations will appear here. Uncertain or rejected evidence stays available in Observations.</p><a class="button" href="#import">Import evidence</a>');
  }else if(route==='targets'){
   const targets=await api('targets?archived=1');html=panel('Add or update a target',`<p class="muted">Saving an existing URL updates its label and threshold. Collection and notifications are not configured.</p><form id="target-form"><div class="form-grid"><label>Label<input name="label" required maxlength="120" placeholder="27-inch display"></label><label>Target item price, USD (optional)<input name="price" inputmode="decimal" placeholder="799.99"></label><label class="full">Clean product URL<input name="url" type="url" required maxlength="2048" placeholder="https://www.bestbuy.com/site/…"></label></div><button>Save target</button></form>`)+panel('Saved targets',targets.length?targets.map(t=>`<div class="target-item"><div><strong>${e(t.label)}</strong>${t.archived?' <span class="badge">Archived</span>':''}<small>${e(t.url)}</small><p>Target: ${t.targetMinor===null?'Not set':money(t.targetMinor)} <small>No automated collection</small></p></div><button class="secondary" data-target="${e(t.id)}" data-archived="${t.archived?'0':'1'}">${t.archived?'Restore target':'Archive'}</button></div>`).join(''):'<p class="muted">No targets saved yet.</p>');
  }else if(route==='import'){
   html=panel('Import a saved capture',`<form id="import-form"><div class="form-grid"><label>Capture format<select name="format" id="import-format"><option value="json">Normalized JSON</option><option value="html">Saved HTML + metadata</option></select></label><label>Capture file<input name="capture" type="file" accept=".json,.html,.htm" required></label><label id="metadata-field" class="full" hidden>Metadata JSON<input name="metadata" type="file" accept=".json"></label><label class="full">Historical evaluation time (optional)<input name="at" type="datetime-local" step="1"><small>Uses your browser's local time zone. Leave empty to enforce current freshness. Replay does not make an old price current.</small></label></div><p class="muted">Raw HTML is parsed locally without running its scripts. Maximum capture file: 2 MiB. No upload to GitHub or any other service.</p><button>Validate and import</button></form>`)+panel('What belongs in a capture?','<p>A capture describes the exact product and variant, seller, condition, availability, price, eligibility, fulfillment and when it was observed. Missing context is kept unknown.</p><p>JSON-LD alone is insufficient for acceptance. See the repository README for the capture contract and saved-HTML metadata format.</p><button class="secondary" data-action="demo">Load synthetic sample</button>');
  }else{
   html=panel('Export a private backup','<p>Download observations, correction events and watch targets as a checksummed JSON archive. Store this file privately; it contains your research data and is not encrypted.</p><button data-action="backup">Download backup</button><small>Up to 5,000 observations, 50,000 decisions and 1,000 targets per archive.</small>')+panel('Restore into a new database','<p>Stop the app before switching databases. Restore uses a new file and refuses to overwrite an existing database.</p><pre>npm run cli -- restore --file backups/research.pi-backup.json --db data/restored.sqlite\nnpm start -- --db data/restored.sqlite</pre><p class="muted">The checksum detects accidental corruption. Only restore archives you trust. Original captures are revalidated at their recorded evaluation times; history remains historical.</p>');
  }
  if(ticket===generation)screen.innerHTML=html;
 }catch(error){if(ticket===generation){if(!token)authScreen();else screen.innerHTML=panel('Unable to load this view','<p>Please retry with Refresh. Your existing evidence has not been removed.</p>');notice(error.message,true);}}finally{if(ticket===generation)screen.removeAttribute('aria-busy');}
}
async function showObservation(id,append=false){
 const previous=append?activeDetail:null;return detailGate.run(()=>api('observation?'+params({id,after:previous?.nextCursor})),data=>{if(append)data.decisions=[...previous.decisions,...data.decisions];activeDetail=data;
 $('detail-title').textContent=productName(data.capture.context.product);const c=data.capture,v=data.evaluation;
 $('detail-content').innerHTML=`<p>${badge(data.currentStatus,c.synthetic)} <small>${e(ageLabel(c.observedAt))}</small></p><dl>${[['Observed',date(c.observedAt)],['Listing',c.url],['Selected variant',c.context.product.variant],['Seller',c.context.seller],['Condition',c.context.condition],['Fulfillment',c.context.fulfillment],['Eligibility',c.context.eligibility],['Accepted item price',v.offer?money(v.offer.priceMinor):'None'],['Original reasons',v.reasons.join(', ')]].map(([k,value])=>`<dt>${k}</dt><dd>${e(value??'Unknown')}</dd>`).join('')}</dl><h3>Candidate evidence</h3><div class="table-wrap"><table><thead><tr><th>Price / role</th><th>Source / origin</th><th>Context</th><th>Locator</th></tr></thead><tbody>${c.candidates.map(x=>`<tr><td>${e(x.price??'Unknown')} ${e(x.currency??'')}<small>${e(x.role)}</small></td><td>${e(x.source)}<small>${e(x.origin)}</small></td><td>${e(x.seller??'Unknown seller')}<small>${e(x.product.variant??'Unknown variant')} · ${e(x.condition??'Unknown condition')} · ${e(x.availability??'Unknown availability')}</small></td><td>${e(x.locator)}</td></tr>`).join('')}</tbody></table></div><details><summary>Supporting and excluded evidence</summary><pre>${e(JSON.stringify({supporting:v.supporting,excluded:v.excluded,issues:c.issues},null,2))}</pre></details><h3>Decision history (${data.decisionCount})</h3><ol>${data.decisions.map(d=>`<li>${badge(d.status)} ${e(d.reason)}<small>${e(date(d.decidedAt))}</small></li>`).join('')}</ol>${data.nextCursor!==null?'<button class="secondary" data-action="decisions-more">More decisions</button>':''}<h3>Append a review decision</h3><form id="decision-form"><div class="form-grid"><label>Review status<select name="status"><option value="uncertain">Uncertain</option><option value="rejected">Rejected</option>${v.status==='accepted'?'<option value="accepted">Restore accepted</option>':''}</select></label><label>Reason<select name="reason"><option>RECHECK_REQUIRED</option><option>WRONG_PRODUCT</option><option>WRONG_PRICE</option><option>RECHECK_CONFIRMED</option></select></label></div><button>Save review decision</button><small>Original evidence is immutable. Originally uncertain captures cannot be promoted without new evidence.</small></form><p id="detail-notice" role="status"></p>`;
 if(!dialog.open)dialog.showModal();return true;
 });
}
async function showHistory(index,append=false){const group=historyRows[index];return detailGate.run(()=>api('series',{key:group.offerKey,includeSynthetic:$('synthetic').checked,after:append?seriesNext:undefined,limit:200}),data=>{seriesRows=append?[...seriesRows,...data.items]:data.items;seriesNext=data.nextCursor;$('detail-title').textContent=productName(group.product);$('detail-content').innerHTML=`<p>${e(group.seller)} · ${e(group.condition)} · ${e(group.fulfillment)} ${group.containsSynthetic?badge('synthetic'):''}</p><p class="muted">Observed item prices. Shipping and tax unknown.</p>${priceChart(seriesRows)}<div class="table-wrap"><table><thead><tr><th>Observed</th><th>Item price</th><th>Evidence</th></tr></thead><tbody>${seriesRows.map(r=>`<tr><td>${e(date(r.observedAt))}</td><td class="number">${money(r.priceMinor)}</td><td><button class="link" data-observation="${e(r.id)}">Inspect capture</button></td></tr>`).join('')}</tbody></table></div>${seriesNext!==null?`<button class="secondary" data-series-more="${index}">More price points</button>`:''}`;if(!dialog.open)dialog.showModal();});}
// Internal renders may overlap saves; only newer user view choices cancel refreshes.
async function action(button){const currentView=viewGate.checkpoint();button.disabled=true;try{
 if(button.dataset.observation)await showObservation(button.dataset.observation);
 else if(button.dataset.history!==undefined)await showHistory(Number(button.dataset.history));
 else if(button.dataset.seriesMore!==undefined)await showHistory(Number(button.dataset.seriesMore),true);
 else if(button.dataset.target){await api('targets/archive',{id:button.dataset.target,archived:button.dataset.archived==='1'});if(currentView())await render();}
 else if(button.dataset.action==='more')await render(false);
 else if(button.dataset.action==='decisions-more')await showObservation(activeDetail.capture.id,true);
 else if(button.dataset.action==='demo'){await api('demo',{});notice('Synthetic sample loaded. It is excluded whenever synthetic data is turned off.');if(currentView()){$('synthetic').checked=true;if(location.hash==='#overview')await render();else location.hash='overview';}}
 else if(button.dataset.action==='backup'){const data=await api('backup'),url=URL.createObjectURL(new Blob([archiveText(data)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='product-intelligence.pi-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notice('Backup downloaded. Keep it outside the public repository.');}
 }catch(error){notice(error.message,true);if(dialog.open&&$('detail-notice'))$('detail-notice').textContent=error.message;}finally{button.disabled=false;}}
document.addEventListener('click',event=>{const b=event.target.closest('button[data-action],button[data-observation],button[data-history],button[data-target],button[data-series-more]');if(b)void action(b);});
document.addEventListener('submit',async event=>{
 const form=event.target;if(!['search-form','target-form','import-form','decision-form'].includes(form.id))return;event.preventDefault();const data=new FormData(form),button=form.querySelector('button'),pageAtSubmit=generation,currentView=viewGate.checkpoint();button.disabled=true;notice('');try{
 if(form.id==='search-form'){viewGate.cancel();filters={query:String(data.get('query')),status:String(data.get('status'))};await render();}
 else if(form.id==='target-form'){await api('targets',{url:String(data.get('url')),label:String(data.get('label')),targetMinor:targetPrice(String(data.get('price')))});notice('Watch target saved. Automated collection is not configured.');if(currentView())await render();}
 else if(form.id==='decision-form'){const id=activeDetail.capture.id,current=detailGate.checkpoint();await api('decisions',{id,status:data.get('status'),reason:data.get('reason')});if(current()){const applied=await showObservation(id);if(applied&&activeDetail.capture.id===id&&$('detail-notice'))$('detail-notice').textContent='Review decision saved.';}if(currentView())await render();}
 else{const file=data.get('capture');if(!file?.size||file.size>2*1024*1024)throw new Error('Choose a capture file up to 2 MiB.');const text=await file.text(),html=data.get('format')==='html';let payload;
  if(html){const metadata=data.get('metadata');if(!metadata?.size||metadata.size>128*1024)throw new Error('Choose metadata JSON up to 128 KiB.');payload={html:text,metadata:JSON.parse(await metadata.text())};}else payload={capture:JSON.parse(text)};
  if(data.get('at'))payload.at=new Date(String(data.get('at'))).toISOString();const result=await api(html?'import-html':'import',payload);notice((result.duplicate?'Capture already exists.':'Capture imported.')+' Review status: '+result.evaluation.status+'.');if(generation===pageAtSubmit)await showObservation(result.id);
 }
 }catch(error){const message=error instanceof SyntaxError?'The selected file is not valid JSON.':error.message;notice(message,true);if(dialog.open&&$('detail-notice'))$('detail-notice').textContent=message;}finally{button.disabled=false;}
});
document.addEventListener('change',event=>{if(event.target.id==='import-format'){$('metadata-field').hidden=event.target.value!=='html';$('metadata-field').querySelector('input').required=event.target.value==='html';}});
$('skip-link').onclick=event=>{event.preventDefault();$('content').focus();};
dialog.addEventListener('close',()=>detailGate.cancel());dialog.addEventListener('cancel',()=>detailGate.cancel());$('close-detail').onclick=()=>{detailGate.cancel();dialog.close();};$('refresh').onclick=()=>{viewGate.cancel();void render();};$('synthetic').onchange=()=>{viewGate.cancel();detailGate.cancel();if(dialog.open)dialog.close();void render();};window.addEventListener('hashchange',()=>{viewGate.cancel();consumeSessionLink();detailGate.cancel();notice('');if(dialog.open)dialog.close();void render();});void render();
